COPY podm_pfas_data(sample_id,pfna_concentration,pfna_mrl,pfna_dl,pfna_flags,pfds_concentration,pfds_mrl,pfds_dl,pfds_flags,pfhxa_concentration,pfhxa_mrl,pfhxa_dl,pfhxa_flags,pfoa_concentration,pfoa_mrl,pfoa_dl,pfoa_flags,pfos_concentration,pfos_mrl,pfos_dl,pfos_flags,pfba_concentration,pfba_mrl,pfba_dl,pfba_flags,pfdoa_concentration,pfdoa_mrl,pfdoa_dl,pfdoa_flags,pfpea_concentration,pfpea_mrl,pfpea_dl,pfpea_flags,pfhps_concentration,pfhps_mrl,pfhps_dl,pfhps_flags,pfunda_concentration,pfunda_mrl,pfunda_dl,pfunda_flags,pfbs_concentration,pfbs_mrl,pfbs_dl,pfbs_flags,pfpes_concentration,pfpes_mrl,pfpes_dl,pfpes_flags,pfns_concentration,pfns_mrl,pfns_dl,pfns_flags,pfhpa_concentration,pfhpa_mrl,pfhpa_dl,pfhpa_flags,pfhxs_concentration,pfhxs_mrl,pfhxs_dl,pfhxs_flags,pfda_concentration,pfda_mrl,pfda_dl,pfda_flags)
FROM '/projects/pfas/data/AHHS_Dust_DataCleaned_231020_nmd_Column.csv'
DELIMITER ','
CSV HEADER;

COPY podm_pfas_data(sample_id,pfhps_concentration,pfhps_mrl,pfhps_dl,pfhps_flags,pfhxs_concentration,pfhxs_mrl,pfhxs_dl,pfhxs_flags,pfda_concentration,pfda_mrl,pfda_dl,pfda_flags,pfba_concentration,pfba_mrl,pfba_dl,pfba_flags,pfpea_concentration,pfpea_mrl,pfpea_dl,pfpea_flags,pfpes_concentration,pfpes_mrl,pfpes_dl,pfpes_flags,pfna_concentration,pfna_mrl,pfna_dl,pfna_flags,pfhxa_concentration,pfhxa_mrl,pfhxa_dl,pfhxa_flags,pfbs_concentration,pfbs_mrl,pfbs_dl,pfbs_flags,pfos_concentration,pfos_mrl,pfos_dl,pfos_flags,pfhpa_concentration,pfhpa_mrl,pfhpa_dl,pfhpa_flags,pfoa_concentration,pfoa_mrl,pfoa_dl,pfoa_flags,pfns_concentration,pfns_mrl,pfns_dl,pfns_flags)
FROM '/projects/pfas/data/AHHS_Water_DataCleaned_231020_nmd_Column.csv'
DELIMITER ','
CSV HEADER;

COPY podm_pfas_data(sample_id,pfba_concentration,pfba_mrl,pfba_dl,pfba_flags,pfbs_concentration,pfbs_mrl,pfbs_dl,pfbs_flags,pfda_concentration,pfda_mrl,pfda_dl,pfda_flags,pfdoa_concentration,pfdoa_mrl,pfdoa_dl,pfdoa_flags,pfds_concentration,pfds_mrl,pfds_dl,pfds_flags,pfhpa_concentration,pfhpa_mrl,pfhpa_dl,pfhpa_flags,pfhps_concentration,pfhps_mrl,pfhps_dl,pfhps_flags,pfhxa_concentration,pfhxa_mrl,pfhxa_dl,pfhxa_flags,pfhxs_concentration,pfhxs_mrl,pfhxs_dl,pfhxs_flags,pfna_concentration,pfna_mrl,pfna_dl,pfna_flags,pfns_concentration,pfns_mrl,pfns_dl,pfns_flags,pfoa_concentration,pfoa_mrl,pfoa_dl,pfoa_flags,pfos_concentration,pfos_mrl,pfos_dl,pfos_flags,pfpea_concentration,pfpea_mrl,pfpea_dl,pfpea_flags,pfpes_concentration,pfpes_mrl,pfpes_dl,pfpes_flags,pfunda_concentration,pfunda_mrl,pfunda_dl,pfunda_flags)
FROM '/projects/pfas/data/NCSDust_output_Column.csv'
DELIMITER ','
CSV HEADER;

COPY podm_pfas_data(sample_id,pfba_concentration,pfba_mrl,pfba_dl,pfba_flags,pfbs_concentration,pfbs_mrl,pfbs_dl,pfbs_flags,pfda_concentration,pfda_mrl,pfda_dl,pfda_flags,pfdoa_concentration,pfdoa_mrl,pfdoa_dl,pfdoa_flags,pfds_concentration,pfds_mrl,pfds_dl,pfds_flags,pfhpa_concentration,pfhpa_mrl,pfhpa_dl,pfhpa_flags,pfhps_concentration,pfhps_mrl,pfhps_dl,pfhps_flags,pfhxa_concentration,pfhxa_mrl,pfhxa_dl,pfhxa_flags,pfhxs_concentration,pfhxs_mrl,pfhxs_dl,pfhxs_flags,pfna_concentration,pfna_mrl,pfna_dl,pfna_flags,pfns_concentration,pfns_mrl,pfns_dl,pfns_flags,pfoa_concentration,pfoa_mrl,pfoa_dl,pfoa_flags,pfos_concentration,pfos_mrl,pfos_dl,pfos_flags,pfpea_concentration,pfpea_mrl,pfpea_dl,pfpea_flags,pfpes_concentration,pfpes_mrl,pfpes_dl,pfpes_flags,pfunda_concentration,pfunda_mrl,pfunda_dl,pfunda_flags)
FROM '/projects/pfas/data/NCSSerum_output_Column_Corrected_SampleID.csv'
DELIMITER ','
CSV HEADER;
