INSERT INTO podm_pfas_data (sample_id,pfba_concentration,pfba_mrl,pfbs_concentration,pfbs_mrl,pfda_concentration,pfda_mrl,pfdoa_concentration,pfdoa_mrl,pfhpa_concentration,pfhpa_mrl,pfhps_concentration,pfhps_mrl,pfhxa_concentration,pfhxa_mrl,pfhxs_concentration,pfhxs_mrl,pfna_concentration,pfna_mrl,pfoa_concentration,pfoa_mrl,pfos_concentration,pfos_mrl,pfpea_concentration,pfpea_mrl,pfpes_concentration,pfpes_mrl)
SELECT unique_id AS sample_id, 
      pfba_concentration_ngl AS pfba_concentration,
      pfba_mrl_ngl AS pfba_mrl,
      pfbs_concentration_ngl AS pfbs_concentration,
      pfbs_mrl_ngl AS pfbs_mrl,
      pfda_concentration_ngl AS pfda_concentration,
      pfda_mrl_ngl AS pfda_mrl,
      pfdoa_concentration_ngl AS pfdoa_concentration,
      pfdoa_mrl_ngl AS pfdoa_mrl,
      pfhpa_concentration_ngl AS pfhpa_concentration,
      pfhpa_mrl_ngl AS pfhpa_mrl,
      pfhps_concentration_ngl AS pfhps_concentration,
      pfhps_mrl_ngl AS pfhps_mrl,
      pfhxa_concentration_ngl AS pfhxa_concentration,
      pfhxa_mrl_ngl AS pfhxa_mrl,
      pfhxs_concentration_ngl AS pfhxs_concentration,
      pfhxs_mrl_ngl AS pfhxs_mrl,
      pfna_concentration_ngl AS pfna_concentration,
      pfna_mrl_ngl AS pfna_mrl,
      pfoa_concentration_ngl AS pfoa_concentration,
      pfoa_mrl_ngl AS pfoa_mrl,
      pfos_concentration_ngl AS pfos_concentration,
      pfos_mrl_ngl AS pfos_mrl,
      pfpea_concentration_ngl AS pfpea_concentration,
      pfpea_mrl_ngl AS pfpea_mrl,
      pfpes_concentration_ngl AS pfpes_concentration,
      pfpes_mrl_ngl AS pfpes_mrl
FROM landing_usmr5_data;
