CREATE TABLE IF NOT EXISTS podm_pfas_data2 (
    data_id SERIAL PRIMARY KEY,
    sample_id VARCHAR(100),
    pfmpa_concentration NUMERIC,
    pfmpa_mrl NUMERIC,
    pfmba_concentration NUMERIC,
    pfmba_mrl NUMERIC,
    pfta_concentration NUMERIC,
    pfta_mrl NUMERIC,
    netfosaa_concentration NUMERIC,
    netfosaa_mrl NUMERIC,
    x82fts_concentration NUMERIC,
    x82fts_mrl NUMERIC,
    hfpoda_concentration NUMERIC,
    hfpoda_mrl NUMERIC,
    x62fts_concentration NUMERIC,
    x62fts_mrl NUMERIC,
    nfdha_concentration NUMERIC,
    nfdha_mrl NUMERIC,
    pfuna_concentration NUMERIC,
    pfuna_mrl NUMERIC,
    pfeesa_concentration NUMERIC,
    pfeesa_mrl NUMERIC,
    nmefosaa_concentration NUMERIC,
    nmefosaa_mrl NUMERIC,
    x9clpf3ons_concentration NUMERIC,
    x9clpf3ons_mrl NUMERIC,
    x11clpf3ouds_concentration NUMERIC,
    x11clpf3ouds_mrl NUMERIC,
    adona_concentration NUMERIC,
    adona_mrl NUMERIC,
    x42fts_concentration NUMERIC,
    x42fts_mrl NUMERIC,
    pftrda_concentration NUMERIC,
    pftrda_mrl NUMERIC,
    genx_concentration NUMERIC, 
    fosa_concentration NUMERIC, 
    f6_2fts_concentration NUMERIC, 
    pfprs_concentration NUMERIC
);

CREATE INDEX IF NOT EXISTS pfas_data2_sample_id_index
ON podm_pfas_data2(sample_id);
